"""add appearance_tag to book_characters

Revision ID: a3a73d9a5acd
Revises: 86cd5c7a38a3
Create Date: 2026-02-16 07:08:49.588363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a73d9a5acd'
down_revision: Union[str, None] = '86cd5c7a38a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_characters', sa.Column('appearance_tag', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_characters', 'appearance_tag')
    # ### end Alembic commands ###
